# GitHub Actions Workflow created for handling the release process based on the draft release prepared with the Build workflow.
# Running the publishPlugin task requires all following secrets to be provided: PUBLISH_TOKEN, PRIVATE_KEY, PRIVATE_KEY_PASSWORD, CERTIFICATE_CHAIN.
# See https://plugins.jetbrains.com/docs/intellij/plugin-signing.html for more information.

name: Build Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Build Plugin
        run: |
          VERSION=${{ github.ref_name }}
          ./gradlew buildPlugin -PpluginVersion="${VERSION:1}"

      - name: Publish Release
        env:
          DIST_DIR: "./build/distributions"
        run: |
          VERSION=${{ github.ref_name }}
          PROJECT_NAME="$(basename ${{ github.repository }})"
          PKG="$PROJECT_NAME-${VERSION:1}.zip"
          ls -l "$DIST_DIR"
          gh release create ${{ github.ref_name }} "$DIST_DIR/$PKG" --generate-notes